Revert "Switch from distutils to setuptools to fix namespace package issues"
This reverts commit 866c600a9fe3dd9016fcab94cd0333f60fa53652.

This patch causes the test suite to fail with

Traceback (most recent call last):
  File "/home/kipp/local/bin/ligolw_print", line 4, in <module>
    __import__('pkg_resources').run_script('python-ligo-lw==1.7.0', 'ligolw_print')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1451, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/ligolw_print' not found in metadata at None